feat: add liqduiity over time resolver
galacticcouncil/Basilisk-api-old pull request #16
Opened 2021-11-10 10:26 UTC by enthusiastmartin

2021-11-10 18:51 UTC, maht0rz requested changes

2021-11-10 18:51 UTC, maht0rz commented on package.json
> +    "test:resolver": "mocha -r ts-node/register src/test/**.test.ts"
I'd recommend we add a watch version of this script - also please rename the test files to `.spec.ts` like in the `processor:test`.

Generally speaking, it'd also make sense to unify the resolver & processor tests under one command, just `npm run test` instead of two separate commands.

2021-11-10 18:51 UTC, maht0rz commented on schema.graphql
> +type TestBlock @entity {
I don't know how to deal with this exactly, but we can't allow for the `TestBlock` to make it to the production database. It'd be queryable through the gql node and would look really bad.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +export class Entry{
Probably add a space after `Entry`

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +  at!: string
is this `createdAt`? If so, probably should be renamed.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +  block_height: string,
Please convert this to camelCase instead, this applies to every variable or function basically.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +  TABLE: string = "test_block";
this needs to be parametrisable, can be done via the class constructor.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +export class LiquidityOverTimeResolver {
I'd suggest we change the class name to something more generic, i suspect liquidity over time will not be the only historical entitry we'll query in this fashion.

We will probably need a more complex resolver for historical volume, but that is not relevant yet/now.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +      @InjectManager() private db: EntityManager,
instead of this you're using `getManager()` which probably comes from extending some `BaseResolver` via the `@Resolver` annotation, so this can be removed.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +
this empty line can be removed

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +  chunk_size_in_seconds(from: string, to:string, quantity: number): number{
please convert this to camelCase

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +    return diff / 1000 / quantity;
What does the `1000` stand for? Can we please extract this to a constant, or make it a class property/variable? (same as `TABLE/TIME_FIELD`)

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +  @Query(() => [Entry])
Looks like you need to provide an `Entry/Entity` that you're returning, since we want to generalize this, we should use a factory or a similar pattern to deal with the problem above.

Here's an example (valid js that compiles):
```
const resolver = function historicalEntityResolverFactory(entity) {
  // use `entity` in the decorators as required
  return class Test {
   
  }
}
```

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +      @Arg("from", { defaultValue: new Date().toISOString() }) from: string,
I'd vote we make this non nullable as well, good to know that we can provide a defaultValue, but it is probably counter intuitive since it'd only return the current data, if there is any.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +
extra space probably can be removed

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +
plus a space before `QueryResult[]`

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +
I think if you apply the factory pattern mentioned in an earlier comment, then you could use TypeScript generics + the generated models from `src/generated/model` instead of having to create your own `Entity` model.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +
@lumir-mrkva can you please lend us your SQL-eye and review the SQL query below? My SQL skills are limited at the very best.

2021-11-10 18:51 UTC, maht0rz commented on src/server-extension.ts
> +      return new Entry(val.block_height, "200", val.created_at.toISOString())
Looks like the liquidity here is static, this will be solved with the generalisation of the resolver. [Here are some tips on how to create a `new` instance on a class name that gets passed as a parameter](https://stackoverflow.com/questions/1606797/use-of-apply-with-new-operator-is-this-possible)

2021-11-10 18:51 UTC, maht0rz commented on src/test/util/setup.ts
> +async function withClient(block: (client: ClientBase) => Promise<void>): Promise<void> {
can we steal more of this from subsquid, or do they not export those helpers or are we using a thinned down version for our purposes?

2021-11-10 18:51 UTC, maht0rz commented on src/test/util/setup.ts
> +        await client.query(`TRUNCATE TABLE test_block`)
would be cool if this was all parametrised, since this won't be the only resolver we'll be implementing (i suspect)

2021-11-10 18:51 UTC, maht0rz commented on src/test/util/setup.ts
> +        if ( extensionModule) {
extra space can be removed here

2021-11-10 18:51 UTC, maht0rz commented on src/test/util/setup.ts
> +        process.env.DB_PORT ? parseInt(process.env.DB_PORT) : 5432,
probably would be ideal to extract constants like ports

2021-11-10 18:51 UTC, maht0rz commented on src/test/reolver.test.ts
> +            //`CREATE TABLE ${table_name} ("id" character varying NOT NULL, "block_height" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "pk_constraint" PRIMARY KEY ("i
Not sure what the problem here was with creating the tables, did you figure it out in the end, or were you creating tables manually all the time?

2021-11-10 18:51 UTC, maht0rz commented on src/test/reolver.test.ts
> +            `insert into ${table_name} (id, block_height, created_at) values (0, 0, '2021-07-11T11:00:00')`,
Can we construct the query from a dataset as an array? I think you could even construct the dataset programatically together with the expected results at the end of the tests. To keep things DRY

2021-11-10 18:51 UTC, maht0rz commented on src/test/reolver.test.ts
> +        const client = useServer()
This should be moved to a beforeEach, you can nest `describe()` calls to define tests in a nested structure with `beforeEach/beforeAll/afterEach/afterAll` for each level individually (+ inherited from the parent describe)

2021-11-12 12:33 UTC, enthusiastmartin commented on schema.graphql
> +type TestBlock @entity {
This can be done in separate issue after this effotr is merged.

The test can create and drop its table during the test.

2021-11-12 12:33 UTC, enthusiastmartin commented on src/server-extension.ts
> +    return diff / 1000 / quantity;
Time diff is in ms. It is to get seconds.

2021-11-12 12:37 UTC, enthusiastmartin commented on package.json
> +    "test:resolver": "mocha -r ts-node/register src/test/**.test.ts"
done

2021-11-12 12:39 UTC, enthusiastmartin commented on src/server-extension.ts
> +      @Arg("from", { defaultValue: new Date().toISOString() }) from: string,
done

2021-11-29 23:15 UTC, merged